# Generated by Django 3.0 on 2019-12-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind_user',
            name='e_data',
        ),
    ]
