# Generated by Django 3.0 on 2019-12-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_ind_user_e_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_user',
            name='document',
            field=models.FileField(default='../Ind_User_Data.xlsx', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
