# Generated by Django 3.0 on 2019-12-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ind_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_user',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
