# Generated by Django 3.0 on 2019-12-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191228_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind_user',
            name='document',
        ),
        migrations.AddField(
            model_name='ind_user',
            name='e_file',
            field=models.FileField(default='Ind_User_Data.xlsx', upload_to='uploads/'),
        ),
    ]
